### ISSUE TITLE
task priority query

### ISSUE THREAD

**Issue by kiranpradeep** [Naios/TaskScheduler#1]
1.What I miss is, we cannot safely schedule a high-frequency task along with a long running task. For e.g consider a high-frequency task which needs to run every 1 seconds. Then if some one adds a run-once task which takes 10sec to run, then the high-frequency task cannot be scheduled properly. A thread-pool is missing. May be, this library is for different use cases.

**Comment by Naios** [comment]
The library was designed to work in a non-critical context and thus it is not recommended to use it as scheduler for a thread-pool. Although it is possible to use it across multiple threads however this would require heavy locking. Consider boost asio's deadline timer as alternative.
