### ISSUE TITLE
Incorrect min > max Exception if there are different time types

### ISSUE THREAD

**Issue by Markus2k** [Naios/TaskScheduler#2]
Greetings Denis,

Thanks for your work, the interface looks very nice and is easy to use.

I think I found an issue within your implementation.
If I schedule a task with a randomized time frame which has two different time types (Seconds / Minutes ...) I get an exception.
It seems like the min / max comparison does not take that into consideration.
If I change the values to the same time type its working fine.

I also have two questions regarding features. 
Perhaps they exist, but I did not find them.

1. Have you thought about an automatic updated interval. So that the loop is configured once and works with that update interval until changed.

2. Is there a way to remove the requirement for the update function call, so that the worker waits on a condition which is the next timed task or a queue interaction.

Best Wishes,
Markus

**Comment by Naios** [comment]
Hi Markus,
thanks a lot for your issue report. Sadly I didn't take a look at this repository for a while.
I fixed your issue in 2896a8ffd1 and it seems that it was a really critical issue.
Best, Denis
