### ISSUE TITLE
Error C3848.

### ISSUE THREAD

**Issue by IceShiva** [Naios/TaskScheduler#3]
I would like to use your scheduler for my application but I found little trouble with compiling the code using Microsoft Visual Studio Community 2019.  Compiler says:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1467,1): error C3848: expression having type 'const tsc::TaskScheduler::Compare' would lose some const-volatile qualifiers in order to call 'bool tsc::TaskScheduler::Compare::operator ()(const tsc::TaskScheduler::TaskContainer &,const tsc::TaskScheduler::TaskContainer &)'`

I fixed issue by adding const qualifier for operator() in Compare struct. Now code seems to compile but I cannot confirm it's works fine.
Best Regards.

**Comment by bascoder** [comment]
@IceShiva can you include the exact code changes you made?

By the way, I had to include `#include <functional>` in `TaskScheduler.hpp` to fix some compiler errors.

**Comment by IceShiva** [comment]
Hello. Sure

 Location in orginal code https://github.com/Naios/TaskScheduler/blob/2896a8ffd1cf628cb28271990808b08aff30a452/src/TaskScheduler.hpp#L160

Fixed code:

    struct Compare
    {
        bool operator() (TaskContainer const& left, TaskContainer const& right) const
        {
            return (*left.get()) < (*right.get());
        };
    };

**Comment by bascoder** [comment]
> 
> 
> Hello. Sure
> 
> Location in orginal code
> 
> https://github.com/Naios/TaskScheduler/blob/2896a8ffd1cf628cb28271990808b08aff30a452/src/TaskScheduler.hpp#L160
> 
> Fixed code:
> 
> ```
> struct Compare
> {
>     bool operator() (TaskContainer const& left, TaskContainer const& right) const
>     {
>         return (*left.get()) < (*right.get());
>     };
> };
> ```

Thanks, now it compiles! 😄

**Comment by Naios** [comment]
It seems like this issue was resolved.
